---

LENG_PRIMARY: '  AC  AB   F   R  AG Int Vol Sim'
LENG_SECONDARY: '   A  Fe  BF  BR   M Mag Fol  PF'
LENG_EXPLAIN: 'Questi sono i risultati al termine della simulazione'


#LIFE POINT
LENG_WOUNDS: 'punti vita'

#Fighter alive
LENG_ALIVE: 'rimangono vivi'

#Turn of match
LENG_TURN: 'turni'

LENG_DODGE: 'puo schivare'

LENG_FEND: 'puo parare'
